In [155]:
def readfile(filename):
    file = open(filename, 'rt')
    original_text = file.read()
    file.close()
    
    return original_text

In [156]:
import re
def preprocess_data(text):
    # remove punctuations !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    punctuation_list = ["!","\"","#","$","%","&","'","(",")","*","+",",","-",".","/",":",";","<","=",">","?","@","[","\\","]","^","_","`","{","|","}","~","–","€","•","«","»","’","“","”","£"]
    for punctuation in punctuation_list:
        text = text.replace(punctuation, "")

#     remove numbers
    RE_NUMBERS = re.compile('[0-9]+')
    text = RE_NUMBERS.sub(r'', text)

    # remove emojis
    RE_EMOJI = re.compile('[\U00010000-\U0010ffff]', flags=re.UNICODE)
    text = RE_EMOJI.sub(r'', text) # ⛈ corcra❄ gorm❄

    # substitute multiple spaces with a single space
    text = re.sub(' +', ' ', text)
    
    # trim leading and trailing spaces
    text = text.strip()

    # normalize text to lower case
    text = text.lower()
    
    return text

In [183]:
text = readfile('cleaned_train_2.txt')

# corpus = preprocess_data(corpus)

corpus = text.splitlines()

len(corpus)

456613

In [244]:
vocab = ["a","á","ais","áis","aisti","aistí","ait","áit","ar","ár","arsa","ársa","ban","bán","cead","céad","chas","chás","chuig","chúig","dar","dár","do","dó","gaire","gáire","i","í","inar","inár","leacht","léacht","leas","léas","mo","mó","na","ná","os","ós","re","ré","scor","scór","te","té","teann","téann","thoir","thóir"]
vocab_label_map = {"a": 0, "á": 1, "ais": 2, "áis": 3, "aisti": 4, "aistí": 5, "ait": 6, "áit": 7, "ar": 8, "ár": 9, "arsa": 10, "ársa": 11, "ban": 12, "bán": 13, "cead": 14, "céad": 15, "chas": 17, "chás": 18, "chuig": 19, "chúig": 20, "dar": 21, "dár": 22, "do": 23, "dó": 24, "gaire": 25, "gáire": 26, "i": 27, "í": 28, "inar": 29, "inár": 30, "leacht": 31, "léacht": 32, "leas": 33, "léas": 34, "mo": 35, "mó": 36, "na": 37, "ná": 38, "os": 39, "ós": 40, "re": 41, "ré": 42, "scor": 43, "scór": 44, "te": 45, "té": 46, "teann": 47, "téann": 48, "thoir": 49, "thóir": 50}
pair_to_keyword_example_map = {
    "a|á": { "keywords": ["a","á"], "data": [] },
    "ais|áis": { "keywords": ["ais","áis"], "data": [] },
    "aisti|aistí": { "keywords": ["aisti","aistí"], "data": [] },
    "ait|áit": { "keywords": ["ait","áit"], "data": [] },
    "ar|ár": { "keywords": ["ar","ár"], "data": [] },
    "arsa|ársa": { "keywords": ["arsa","ársa"], "data": [] },
    "ban|bán": { "keywords": ["ban","bán"], "data": [] },
    "cead|céad": { "keywords": ["cead","céad"], "data": [] },
    "chas|chás": { "keywords": ["chas","chás"], "data": [] },
    "chuig|chúig": { "keywords": ["chuig","chúig"], "data": [] },
    "dar|dár": { "keywords": ["dar","dár"], "data": [] },
    "do|dó": { "keywords": ["do","dó"], "data": [] },
    "gaire|gáire": { "keywords": ["gaire","gáire"], "data": [] },
    "i|í": { "keywords": ["i","í"], "data": [] },
    "inar|inár": { "keywords": ["inar","inár"], "data": [] },
    "leacht|léacht": { "keywords": ["leacht","léacht"],  "data": [] },
    "leas|léas": { "keywords": ["leas","léas"], "data": [] },
    "mo|mó": { "keywords": ["mo","mó"], "data": [] },
    "na|ná": { "keywords": ["na","ná"], "data": [] },
    "os|ós": { "keywords": ["os","ós"], "data": [] },
    "re|ré": { "keywords": ["re","ré"], "data": [] },
    "scor|scór": { "keywords": ["scor","scór"], "data": [] },
    "te|té": { "keywords": ["te","té"], "data": [] },
    "teann|téann": { "keywords": ["teann","téann"], "data": [] },
    "thoir|thóir": { "keywords": ["thoir","thóir"], "data": [] },
}
keyword_to_pair_map = {
    "a": "a|á",
    "á": "a|á",
    "ais": "ais|áis",
    "áis": "ais|áis",
    "aisti": "aisti|aistí",
    "aistí": "aisti|aistí",
    "ait": "ait|áit",
    "áit": "ait|áit",
    "ar": "ar|ár",
    "ár": "ar|ár",
    "arsa": "arsa|ársa",
    "ársa": "arsa|ársa",
    "ban": "ban|bán",
    "bán": "ban|bán",
    "cead": "cead|céad",
    "céad": "cead|céad",
    "chas": "chas|chás",
    "chás": "chas|chás",
    "chuig": "chuig|chúig",
    "chúig": "chuig|chúig",
    "dar": "dar|dár",
    "dár": "dar|dár",
    "do": "do|dó",
    "dó": "do|dó",
    "gaire": "gaire|gáire",
    "gáire": "gaire|gáire",
    "i": "i|í",
    "í": "i|í",
    "inar": "inar|inár",
    "inár": "inar|inár",
    "leacht": "leacht|léacht",
    "léacht": "leacht|léacht",
    "leas": "leas|léas",
    "léas": "leas|léas",
    "mo": "mo|mó",
    "mó": "mo|mó",
    "na": "na|ná",
    "ná": "na|ná",
    "os": "os|ós",
    "ós": "os|ós",
    "re": "re|ré",
    "ré": "re|ré",
    "scor": "scor|scór",
    "scór": "scor|scór",
    "te": "te|té",
    "té": "te|té",
    "teann": "teann|téann",
    "téann": "teann|téann",
    "thoir": "thoir|thóir",
    "thóir": "thoir|thóir"
}


In [245]:
type(vocab)

list

In [246]:
X = []
y = []
for sentence in corpus:
    for word in vocab:
        if(word in sentence):
            X.append(sentence)
            y.append(vocab_label_map[word])
            
            key = keyword_to_pair_map[word] # "thoir|thóir"
            pair_to_keyword_example_map[key]["data"].append(sentence)

In [247]:
pair_to_keyword_example_map['a|á']["data"]

['nuair atá cúiseanna á gcur ar an taifead poiblí nó le linn ráiteas poiblí a dhéanamh ní mór don ionchúisitheoir cúram a ghlacadh gan náire a chur ar an gcúisí ná ar fhinnéithe trí eolas a nochtadh nach gcuirfear ar fáil go poiblí murach sin',
 'nuair atá cúiseanna á gcur ar an taifead poiblí nó le linn ráiteas poiblí a dhéanamh ní mór don ionchúisitheoir cúram a ghlacadh gan náire a chur ar an gcúisí ná ar fhinnéithe trí eolas a nochtadh nach gcuirfear ar fáil go poiblí murach sin',
 'tá cinneadh déanta ag killoran agus ag a comhghleacaithe an bhéim a chur ar an drámaíocht agus airgead chiste craoltóireachta na gaeilge á dháileadh',
 'tá cinneadh déanta ag killoran agus ag a comhghleacaithe an bhéim a chur ar an drámaíocht agus airgead chiste craoltóireachta na gaeilge á dháileadh',
 'thug luiz henrique uaquim uachtarán chomharchumann fheirmeoirí an réigiúin bithiúnaigh gléasta suas mar indiaigh ar na tupinambádeolivenáa nuair a chas mé leis',
 'thug luiz henrique uaquim uachtarán ch

In [187]:
# import numpy as np
# from sklearn.feature_extraction.text import HashingVectorizer
# from sklearn.preprocessing import Binarizer
# from keras.preprocessing import sequence

# freq   = HashingVectorizer(binary=False,norm='l1',ngram_range=(1,2))
# X = freq.fit_transform(corpus)

# # x_train = sequence.pad_sequences(X, maxlen=80)
# X[0].shape
# freq.__dict__
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']

from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',categories=categories, shuffle=True, random_state=42)
len(twenty_train.data)

# len(twenty_train.data[0])
# len(twenty_train.data[1])
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(ngram_range=(1,2))
X_train_counts = count_vect.fit_transform(X)
X_train_counts.shape
y = np.array(y)
y.shape

(2104775,)

In [211]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(smooth_idf=True)
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tf.shape

(2104775, 2701025)

In [206]:
import numpy as np
# X = np.random.randint(5, size=(6, 100))
# y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
# X = np.asarray(X)
# y = np.asarray(y)
model = clf.fit(X_train_tfidf, y)
# # MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
# print(clf.predict(X[2:3]))


In [208]:
model.predict(X_train_tfidf)

array([0, 0, 0, ..., 0, 0, 0])

In [202]:
model.predict_proba(X_train_tfidf)[0]

array([7.05447020e-002, 1.35335694e-021, 2.76887685e-039, 9.38658111e-075,
       7.82208492e-081, 2.40733211e-099, 9.89049992e-108, 2.89911832e-033,
       9.29455298e-001, 1.38839108e-053, 1.35088461e-058, 1.06546950e-093,
       3.17896750e-082, 2.21396970e-075, 2.83189808e-035, 1.09269229e-060,
       4.07646251e-089, 5.08590476e-022, 1.01171991e-027, 1.09235048e-096,
       2.09754703e-043, 7.14627975e-054, 4.77248618e-018, 3.05750913e-045,
       1.07303561e-083, 3.46742199e-083, 2.16502845e-012, 2.27784978e-040,
       3.68191795e-037, 1.36054613e-052, 1.24685126e-098, 5.93504962e-091,
       1.13907087e-024, 4.72866437e-080, 3.80101529e-046, 3.94141585e-034,
       1.55523230e-015, 3.10623150e-019, 1.06894964e-035, 1.87667892e-065,
       1.62461422e-103, 1.71695743e-047, 3.23408189e-069, 1.17914954e-064,
       1.11916624e-082, 1.10768369e-041, 4.95894974e-092, 3.81448451e-082,
       6.05180943e-093, 2.72847273e-085])

In [201]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train_counts, y, cv=5, scoring='accuracy')

array([0.2573128 , 0.21131923, 0.21803466, 0.23006459, 0.27573034])

In [209]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train_tfidf, y, cv=5, scoring='accuracy')

array([0.30436797, 0.28871521, 0.28998518, 0.29532459, 0.30951957])

In [214]:
model.predict_proba(X_train_tfidf)
model.predict(X_train_tfidf[0])

array([0])

In [215]:
y[0]

1

In [216]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(ngram_range=(1,2))
corpus_train_counts = count_vect.fit_transform(corpus)
corpus_train_counts.shape

(456613, 2701070)